In [1]:
import numpy as np

In [2]:
# Configure NumPy.
rng = np.random.default_rng(seed=42)
np.set_printoptions(linewidth=100)

### 1 Sample data

In [3]:
data = np.array(
    [
        [3, 6, 1],
        [6, 4, 1],
        [8, 2, 3],
        [7, 5, 3],
        [1, 4, 2],
        [2, 2, 2],
    ]
)
data

array([[3, 6, 1],
       [6, 4, 1],
       [8, 2, 3],
       [7, 5, 3],
       [1, 4, 2],
       [2, 2, 2]])

#### Features

In [4]:
X = data[:, 0:2]
X

array([[3, 6],
       [6, 4],
       [8, 2],
       [7, 5],
       [1, 4],
       [2, 2]])

#### Class Labels

In [5]:
y = data[:, -1].reshape(-1, 1)
y

array([[1],
       [1],
       [3],
       [3],
       [2],
       [2]])

#### Query Point

In [6]:
qp = [2, 5]

### 2 KNN Algorithm

#### STEP #1: Distance b/w query-point & data-points

In [7]:
distances = np.linalg.norm(X - qp, ord=2, axis=1)
distances.tolist()

[1.4142135623730951,
 4.123105625617661,
 6.708203932499369,
 5.0,
 1.4142135623730951,
 3.0]

#### STEP #2: Sort distances in ascending order

In [8]:
mask = distances.argsort(descending=False)
nearest_neignbors = y[mask]

print("Class labels of nearest to farthest neighbors:")
nearest_neignbors

Class labels of nearest to farthest neighbors:


array([[1],
       [2],
       [2],
       [1],
       [3],
       [3]])

#### STEP #3: Pick K number of Neighbors

In [9]:
k = 3
k_nearest_neignbors = nearest_neignbors[:k]
k_nearest_neignbors

array([[1],
       [2],
       [2]])

#### STEP #4: Vote to identify majority class-label

In [10]:
def mode(x):
    values, counts = np.unique(x, return_counts=True)
    mask = np.argmax(counts)
    majority_cl = values[mask]

    return majority_cl

In [11]:
y_pred = mode(k_nearest_neignbors)
print("Predicted class label:", y_pred.item())

Predicted class label: 2
