In [1]:
import numpy as np

In [2]:
# Configure NumPy.
rng = np.random.default_rng(seed=42)
np.set_printoptions(linewidth=100)

#### Sample Data-points

In [3]:
data = np.array(
    [
        [3, 6, 1],
        [6, 4, 1],
        [8, 2, 3],
        [7, 5, 3],
        [1, 4, 2],
        [2, 2, 1],
    ]
)
data

array([[3, 6, 1],
       [6, 4, 1],
       [8, 2, 3],
       [7, 5, 3],
       [1, 4, 2],
       [2, 2, 1]])

In [4]:
x = data[:, 0:2]
x

array([[3, 6],
       [6, 4],
       [8, 2],
       [7, 5],
       [1, 4],
       [2, 2]])

In [5]:
y = data[:, -1]
y

array([1, 1, 3, 3, 2, 1])

In [6]:
qp = [2, 5]

#### Calculate Euclidean Distance

In [7]:
dist = np.linalg.norm(x - qp, ord=2, axis=1)
dist

array([1.41421356, 4.12310563, 6.70820393, 5.        , 1.41421356, 3.        ])

#### Concat Distances and Class-labels

In [8]:
def concate_cols(c1, c2):
    c1 = c1.reshape(-1, 1)
    c2 = c2.reshape(-1, 1)

    return np.hstack((c1, c2))

In [9]:
neignbors = concate_cols(dist, y)
neignbors

array([[1.41421356, 1.        ],
       [4.12310563, 1.        ],
       [6.70820393, 3.        ],
       [5.        , 3.        ],
       [1.41421356, 2.        ],
       [3.        , 1.        ]])

#### Sort Distances

In [10]:
neignbors[:, 0].argsort()

array([0, 4, 5, 1, 3, 2])

In [11]:
def sort_by(x, idx: int, descending=False):
    return x[x[:, idx].argsort(descending=descending)]

In [12]:
sorted_neignbors = sort_by(neignbors, 0)
sorted_neignbors

array([[1.41421356, 1.        ],
       [1.41421356, 2.        ],
       [3.        , 1.        ],
       [4.12310563, 1.        ],
       [5.        , 3.        ],
       [6.70820393, 3.        ]])

#### Vote for Class-labels

In [13]:
def value_count(x, idx):
    labels, votes = np.unique(x[:, idx], return_counts=True)
    return concate_cols(labels, votes)

In [14]:
k = 3
votes = value_count(sorted_neignbors[:k], 1)
top_k = sort_by(votes, 1, descending=True)
top_k

array([[1., 2.],
       [2., 1.]])

In [15]:
y_pred = top_k[0][0]
print("Predicted class label:", y_pred.item())

Predicted class label: 1.0
