# Feature Encoding

In [1]:
import numpy as np

## 1 Introduction

### 1.1 Introduction

#### What is Feature Encoding?

Feature encoding is the data preprocessing process of converting categorical or text-based data into numerical values so that machine learning algorithms can understand and process them.

#### Need for Feature Encoding 

- Categorical variables can be in non numerical values.
- ML Algorithms cannot understand non numerical data hence we need some techniques to convert them to numerical values.
- Feature Encoding **converts non-numerical data into numerical data**.

#### Types of Encoding

Some of the most common feature encoding techniques:

1. Label Encoding
2. One-Hot Encoding
3. Target Encoding
4. Ordinal Encoding

##### Complete taxonomy of Encoding Techniques

```
Categorical Encoding
│
├── 1. Nominal Encoding
│   ├── One-Hot Encoding
│   ├── Dummy Encoding
│   ├── Binary Encoding
│   ├── Base-N Encoding
│   ├── Hash Encoding
│   └── Frequency / Count Encoding
│
├── 2. Ordinal Encoding
│   ├── Ordinal Encoding
│   ├── Label Encoding
│   └── Rank / Ordered Encoding
│
├── 3. Target-Based Encoding
│   ├── Target Mean Encoding
│   ├── Target Probability Encoding
│   ├── Weight of Evidence (WoE)
│   ├── Leave-One-Out Encoding
│   └── CatBoost Encoding
│
├── 4. Contrast / Statistical Encoding
│   ├── Helmert Encoding
│   ├── Sum Encoding
│   ├── Backward Difference Encoding
│   └── Polynomial Contrast Encoding
│
├── 5. Specialized Encoding
│   ├── Feature Hashing
│   ├── Embeddings
│   ├── Entity Embeddings
│   └── Learned Embeddings
│
└── 6. Text / Sequential Encoding
    ├── Bag of Words
    ├── Count Vectorization
    ├── TF-IDF
    ├── N-gram Encoding
    ├── Word Embeddings
    ├── Sentence Embeddings
    └── Transformer Embeddings
```

## 2 Label Encoding

### 2.1 Introduction

#### Properties

1. Label Encoding creates 1 column for each categorical features.
2. Each value in a category gets one numerical value.
3. The original feature is dropped after Label encoding.

#### Advantages

1. Simplest of all encoding techniques, simply replacing text with some number.
2. Original column is replaced with only one column thus not causing Curse of Dimensionality.

#### Disadvantages

1. Creates a **false ordinal relationship** between nominal categories i.e., false ranking assumptions.
2. Label Encoding is **logic less** i.e., the number assigned to a label has no logic/reasoning behind it.

#### API

In [2]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder = LabelEncoder()

### 2.2 Examples

#### Example #1

In [3]:
X = ["A", "C", "A", "A", "C", "D", "D", "D", "B", "D"]
lbl_encoder.fit_transform(X)

array([0, 2, 0, 0, 2, 3, 3, 3, 1, 3])

## 3 One-Hot Encoding

### 3.1 Introduction

#### Properties

1. **Cardinality** is defined as total number of unique values in the feature.
2. One-Hot encoding creates $n$ columns for $n$ unique values in the feature.
3. One-Hot Encoding is preferred when a categorical feature has **low cardinality** (typically fewer than 10 unique values).
4. The **original feature is dropped** after one-hot encoding.
5. The new features created from one-hot encoding is called as **Dummy variables**.

#### Advantages

Feature Encoding **does not introduce false ordinal relationship** between nominal categories.

#### Disadvantages

High cardinality adds too many dimensions (columns) into dataset causing **Curse of Dimensionality**.

#### API

In [4]:
from sklearn.preprocessing import OneHotEncoder

oht_encoder = OneHotEncoder()

### 3.2 Examples

#### Example #1

In [5]:
X = np.array(["A", "C", "A", "A", "C", "E", "D", "D", "B", "D"]).reshape(-1, 1)
oht_encoder.fit_transform(X).toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

## 4 Target Encoding

### 4.1 Introduction

#### Properties

1. As the name suggests "Target" encoding, a categorical feature is encoded using Target variable based some logic.
2. The logic can be some sort of aggregation logic applied using Target variable for each category's group.

#### Advantages

1. Original column is **replaced with only one column** thus not causing Curse of Dimensionality.
2. Feature Encoding **does not introduce false ordinal relationship** between nominal categories.

#### Disadvantages

Requires **Controlled Target Encoding** otherwise can create data leakage between independent and dependent variables.

#### How to avoid data leakage?

https://chatgpt.com/share/6a79ac21-7d04-83ee-be75-cc704415942f

```
      TRAINING DATA
            │
┌───────────┴───────────┐
│                       │
X                       Y
│                       │
└───────┐       ┌───────┘
        ↓       ↓
     Target Encoding
        │
        ↓
    Encoded X
        │
        ↓
      Model
```

#### API

In [6]:
from sklearn.preprocessing import TargetEncoder

tgt_encoder = TargetEncoder(target_type="continuous")

### 4.2 Out-of-Fold Target Encoding

### 4.3 Examples

#### Example #1

In [7]:
X = np.array(["A", "C", "A", "A", "C", "D", "D", "D", "B", "D"]).reshape(-1, 1)
y = np.array([100, 545, 164, 121, 599, 209, 236, 285, 777, 208])
tgt_encoder.fit_transform(X, y)

array([[143.43737597],
       [262.5       ],
       [110.74457574],
       [134.83809479],
       [262.5       ],
       [260.99397779],
       [234.94744415],
       [217.81502185],
       [293.25      ],
       [260.99397779]])

## 5 Ordinal Encoding

### 5.1 Introduction

#### Properties

1. Ordinal Encoding creates 1 column for each categorical features.
2. Each value in a category gets one numerical value.
3. The original feature is dropped after Ordinal encoding.

#### Advantages

1. Users can retain **true or custom ordinal relationship** between nominal categories.
2. Original column is replaced with only one column thus not causing Curse of Dimensionality.

#### API

In [8]:
from sklearn.preprocessing import OrdinalEncoder

ord_encoder = OrdinalEncoder()

### 5.2 Examples

#### Example #1

In [21]:
ord_encoder = OrdinalEncoder()
X = np.array(["A", "C", "A", "A", "C", "D", "D", "D", "B", "D"]).reshape(-1, 1)
ord_encoder.fit_transform(X)

array([[0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [3.],
       [3.],
       [3.],
       [1.],
       [3.]])

#### Example #2

In [20]:
# Retaining true/custom rank: ["D", "C", "B", "A"]
ord_encoder = OrdinalEncoder(categories=[["D", "C", "B", "A"]])
X = np.array(["A", "C", "A", "A", "C", "D", "D", "D", "B", "D"]).reshape(-1, 1)
ord_encoder.fit_transform(X)

array([[3.],
       [1.],
       [3.],
       [3.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.]])

### 5.3 LabelEncoder vs OrdinalEncoder

Difference between LabelEncoder and OrdinalEncoder:

- Ordinal encoding and label encoding both convert categorical text values into integers, but they differ primarily in their intended data types and Scikit-learn API usage.
- `LabelEncoder` is designed to encode one-dimensional target variables (y).
- `OrdinalEncoder` is designed to encode two-dimensional input features (X) and can handle multiple columns at once.

#### LabelEncoder

In [9]:
lbl_encoder = LabelEncoder()
y = ["Yes", "No", "Yes", "Yes", "Yes", "No", "No"]
lbl_encoder.fit_transform(y)

array([1, 0, 1, 1, 1, 0, 0])

#### OrdinalEncoder

In [10]:
X = np.column_stack(
    [
        ["A", "C", "A", "A", "C", "B", "D"],
        ["Blr", "Hyd", "Blr", "Blr", "Chi", "Hyd", "Chi"],
    ]
)
X

array([['A', 'Blr'],
       ['C', 'Hyd'],
       ['A', 'Blr'],
       ['A', 'Blr'],
       ['C', 'Chi'],
       ['B', 'Hyd'],
       ['D', 'Chi']], dtype='<U3')

In [11]:
ord_encoder = OrdinalEncoder()
ord_encoder.fit_transform(X)

array([[0., 0.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [3., 1.]])