# Feature Encoding

In [1]:
import numpy as np

## 1 Introduction

### 1.1 Introduction

#### What is Feature Encoding?

Feature encoding is the data preprocessing process of converting categorical or text-based data into numerical values so that machine learning algorithms can understand and process them.

#### Need for Feature Encoding 

- Categorical variables can be in non numerical values.
- ML Algorithms cannot understand non numerical data hence we need some techniques to convert them to numerical values.
- Feature Encoding **converts non-numerical data into numerical data**.

#### Types of Encoding

Feature Encoding Techniques:

1. Label Encoding
2. One-Hot Encoding
3. Target Encoding

## 2 Label Encoding

### 2.1 Introduction

#### Properties

1. Label Encoding creates 1 column for each categorical features.
2. Each value in a category gets one numerical value.
3. The original feature is dropped after Label encoding.

#### Advantages

1. Simplest of all encoding techniques, simply replacing text with some number.
2. Original column is replaced with only one column thus not causing Curse of Dimensionality.

#### Disadvantages

1. Creates a **false ordinal relationship** between nominal categories i.e., false ranking assumptions.
2. Label Encoding is **logic less** i.e., the number assigned to a label has no logic/reasoning behind it.

#### API

In [2]:
from sklearn.preprocessing import LabelEncoder

lb_encoder = LabelEncoder()

### 2.2 Examples

#### Example #1

In [3]:
x = ["A", "C", "A", "A", "C", "D", "D", "D", "B", "D"]
lb_encoder.fit_transform(x)

array([0, 2, 0, 0, 2, 3, 3, 3, 1, 3])

## 3 One-Hot Encoding

### 3.1 Introduction

#### Properties

1. **Cardinality** is defined as total number of unique values in the feature.
2. One-Hot encoding creates $n$ columns for $n$ unique values in the feature.
3. One-Hot Encoding is preferred when a categorical feature has **low cardinality** (typically fewer than 10 unique values).
4. The **original feature is dropped** after one-hot encoding.
5. The new features created from one-hot encoding is called as **Dummy variables**.

#### Advantages

Feature Encoding **does not introduce false ordinal relationship** between nominal categories.

#### Disadvantages

High cardinality adds too many dimensions (columns) into dataset causing **Curse of Dimensionality**.

#### API

In [4]:
from sklearn.preprocessing import OneHotEncoder

oh_encoder = OneHotEncoder()

### 3.2 Examples

#### Example #1

In [5]:
x = np.array(["A", "C", "A", "A", "C", "E", "D", "D", "B", "D"]).reshape(-1, 1)
oh_encoder.fit_transform(x).toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

## 4 Target Encoding

### 4.1 Introduction

#### Properties

1. As the name suggests "Target" encoding, a categorical feature is encoded using Target variable based some logic.
2. The logic can be some sort of aggregation logic applied using Target variable for each category's group.

#### Advantages

1. Original column is **replaced with only one column** thus not causing Curse of Dimensionality.
2. Feature Encoding **does not introduce false ordinal relationship** between nominal categories.

#### Disadvantages

Requires **Controlled Target Encoding** otherwise can create data leakage between independent and dependent variables.

#### How to avoid data leakage?

https://chatgpt.com/share/6a79ac21-7d04-83ee-be75-cc704415942f

```
      TRAINING DATA
            │
┌───────────┴───────────┐
│                       │
X                       Y
│                       │
└───────┐       ┌───────┘
        ↓       ↓
     Target Encoding
        │
        ↓
    Encoded X
        │
        ↓
      Model
```

#### API

In [6]:
from sklearn.preprocessing import TargetEncoder

tg_encoder = TargetEncoder(target_type="continuous")

### 4.1 Out-of-Fold Target Encoding

### 4.2 Examples

#### Example #1

In [7]:
x = np.array(["A", "C", "A", "A", "C", "D", "D", "D", "B", "D"]).reshape(-1, 1)
y = np.array([100, 545, 164, 121, 599, 209, 236, 285, 777, 208])
tg_encoder.fit_transform(x, y)

array([[143.52097095],
       [262.5       ],
       [100.        ],
       [100.        ],
       [262.5       ],
       [243.82150814],
       [248.28835318],
       [217.76345008],
       [272.75      ],
       [248.28835318]])